name: widget_marker_google_map
description: Customized google map with widget markers. Enables to show markers with widget code.
version: 1.0.0
homepage: https://github.com/santa112358/widget_marker_google_map

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0
  google_maps_flutter_platform_interface: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
